name: Golang Build & Test

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache-dependency-path: go.sum

    - name: Install dependencies
      run: go mod download

    - name: Run CI check
      run: go vet ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -race ./...
